# Generated by Django 5.1.6 on 2025-02-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skipass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skier_name', models.CharField(max_length=100)),
                ('skipass_type', models.CharField(max_length=100)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
