# Generated by Django 5.1.6 on 2025-03-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_skipass_notes_skipass_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkipassOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('duration_days', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='skipass',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
