# Generated by Django 5.1.6 on 2025-03-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skipassoffers_alter_skipass_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkipassOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.IntegerField()),
                ('duration_days', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SkipassOffers',
        ),
    ]
